services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    command: sh -c "npm install && npm run dev"
